### ISSUE TITLE
crop_resize() error

### ISSUE THREAD

**Issue by SravaniTeeparthi29** [ntswj1/DataAugmentation#1]
```
Traceback (most recent call last):
  File "problem7.py", line 565, in <module>
    affine_ten_img, random_ten_param = ten_crop(pil_img, ori_gt)
  File "problem7.py", line 499, in ten_crop
    ori_img, affine_img, cropped_img, new_gt = RAO.all_activities()
  File "problem7.py", line 448, in all_activities
    new_gt)
  File "problem7.py", line 400, in random_occlusion
    new_gt)
  File "problem7.py", line 330, in crop_resize
    crop_img = TF.crop(img,
  File "/home/sravani/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 453, in crop
    raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
TypeError: img should be PIL Image. Got <class 'torch.Tensor'>
```

**Comment by ntswj1** [comment]
Hi, just transform the image to pil image here,  using output=
Image.fromarray(input).
I also updated codes in GitHub by using csv as the input. You can also
check it out.

Wenjing

**Comment by SravaniTeeparthi29** [comment]
```
Traceback (most recent call last):
  File "DataTransformations.py", line 611, in <module>
    main()
  File "DataTransformations.py", line 607, in main
    affine_ten_img, random_ten_param = ten_crop(pil_img, ori_gt)
  File "DataTransformations.py", line 559, in ten_crop
    ori_img, affine_img, cropped_img, new_gt = RAO.all_activities()
  File "DataTransformations.py", line 513, in all_activities
    new_gt)
  File "DataTransformations.py", line 465, in random_occlusion
    new_gt) 
  File "DataTransformations.py", line 400, in crop_resize
    MaxCol-occ_j)
  File "/home/sravani/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 453, in crop
    raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
TypeError: img should be PIL Image. Got <class 'torch.Tensor'>
```

I am still getting the same error with updated code too

**Comment by SravaniTeeparthi29** [comment]
It is a pytorch version problem. For me it worked with version 1.7.1.
